services:
  ml_workspace:
    build:
      context: .
      dockerfile: ./docker/machine_learning.Dockerfile
    image: ml_workspace
    container_name: ml_workspace
    ports:
      - "8888:8888"  # For Jupyter Notebook
    volumes:
      - host_home:/home/ashwin
      - dataset_dir:/datasets
    working_dir: /home/ashwin/workdir
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  host_home:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ashwin
  dataset_dir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ashwin/workdir/datasets

